/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as MerchantProfileRouteImport } from './routes/merchant.profile'
import { Route as MerchantStoresRouteImport } from './routes/merchant.stores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantProfileRoute = MerchantProfileRouteImport.update({
  id: '/merchant/profile',
  path: '/merchant/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantStoresRoute = MerchantStoresRouteImport.update({
  id: '/merchant/stores',
  path: '/merchant/stores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/stores': typeof MerchantStoresRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/stores': typeof MerchantStoresRoute
  '/merchant': typeof MerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/stores': typeof MerchantStoresRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/merchant/profile' | '/merchant/stores' | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/merchant/profile' | '/merchant/stores' | '/merchant'
  id: '__root__' | '/' | '/merchant/profile' | '/merchant/stores' | '/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchantProfileRoute: typeof MerchantProfileRoute
  MerchantStoresRoute: typeof MerchantStoresRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/profile': {
      id: '/merchant/profile'
      path: '/merchant/profile'
      fullPath: '/merchant/profile'
      preLoaderRoute: typeof MerchantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/stores': {
      id: '/merchant/stores'
      path: '/merchant/stores'
      fullPath: '/merchant/stores'
      preLoaderRoute: typeof MerchantStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchantProfileRoute: MerchantProfileRoute,
  MerchantStoresRoute: MerchantStoresRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
